export enum AuditAction {
  SUBMIT = 'SUBMIT',
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  KILL = 'KILL',
  REOPEN = 'REOPEN',
  BLOCK = 'BLOCK',
  ARCHIVE = 'ARCHIVE',
  QA_REVIEW_COMPLETED = 'QA_REVIEW_COMPLETED',
  FINANCE_CONFIRMED = 'FINANCE_CONFIRMED',
  GM_APPROVED = 'GM_APPROVED',
}
