export enum Day30PerformanceFlag {
  BELOW_TARGET = 'BELOW_TARGET',
  GP_ISSUE = 'GP_ISSUE',
  HALT_PO_REQUIRED = 'HALT_PO_REQUIRED',
  ON_TRACK = 'ON_TRACK',
  SIGNIFICANTLY_BELOW = 'SIGNIFICANTLY_BELOW',
}
