export enum GtmOwnerRole {
  CLUSTER_MANAGER = 'CLUSTER_MANAGER',
  FINANCE_MANAGER = 'FINANCE_MANAGER',
  GM_COMMERCIAL_OWNER = 'GM_COMMERCIAL_OWNER',
  MARKETING_GTM_OWNER = 'MARKETING_GTM_OWNER',
  PRODUCT_MANAGER = 'PRODUCT_MANAGER',
}
