export enum PolicyResource {
  PRODUCTS = 'PRODUCTS',
  USERS = 'USERS',
  WORKFLOW = 'WORKFLOW',
  GATE_WORKFLOW = 'GATE_WORKFLOW',
  GATE_THREE_REVIEWS = 'GATE_THREE_REVIEWS',
  GATE_TWO_REVIEWS = 'GATE_TWO_REVIEWS',
  LAUNCH_CONFIRMATIONS = 'LAUNCH_CONFIRMATIONS',
  SELL_IN_REPORTS = 'SELL_IN_REPORTS',
  WEEKLY_FEEDBACK_LOGS = 'WEEKLY_FEEDBACK_LOGS',
  DAY_30_REVIEWS = 'DAY_30_REVIEWS',
  GATE_DECISIONS = 'GATE_DECISIONS',
  AUDIT_LOGS = 'AUDIT_LOGS',
}
