export enum PolicyResource {
  PRODUCTS = 'PRODUCTS',
  USERS = 'USERS',
  WORKFLOW = 'WORKFLOW',
  GATE_WORKFLOW = 'GATE_WORKFLOW',
  GATE_THREE_REVIEWS = 'GATE_THREE_REVIEWS',
  GATE_TWO_REVIEWS = 'GATE_TWO_REVIEWS',
  GATE_DECISIONS = 'GATE_DECISIONS',
  AUDIT_LOGS = 'AUDIT_LOGS',
}
