export enum UserRole {
  ADMIN = 'ADMIN',
  PRODUCT_MANAGER = 'PRODUCT_MANAGER',
  HEAD_OF_PRODUCT = 'HEAD_OF_PRODUCT',
  SOURCING_MANAGER = 'SOURCING_MANAGER',
  QA_TSD_REVIEWER = 'QA_TSD_REVIEWER',
  FINANCE_MANAGER = 'FINANCE_MANAGER',
  GM_COMMERCIAL_OWNER = 'GM_COMMERCIAL_OWNER',
  COO_EXECUTIVE_APPROVER = 'COO_EXECUTIVE_APPROVER',
  MARKETING_GTM_OWNER = 'MARKETING_GTM_OWNER',
  CLUSTER_MANAGER = 'CLUSTER_MANAGER',
  KD_AFTER_SALES = 'KD_AFTER_SALES',
  SPDM_PRODUCT_OPS = 'SPDM_PRODUCT_OPS',
}
